### ISSUE TITLE
Pressing '0' opens the 'Open File Dialog'

### ISSUE THREAD

**Issue by rasmus91** [artemanufrij/graphui#15]
Typing a '0' by releasing the key, in the code field, opens the Open file dialog for me.

taking a quick look at your codebase, it seems this is the course of trouble:

`string[] accel_open = {"<Control>o", "0"};` 

But you seem to set it for Save File also.

When I work with Automatons, i like to make an initual node like this:

`q0 [label="", shape=none];`

And i find it slightly problematic that i can't type a 0

**Comment by artemanufrij** [comment]
hallo @rasmus91, thank you for your feedback. I will check it tonight.

**Comment by artemanufrij** [comment]
@rasmus91, I can't reproduce this bug... could you describe each step, please?
