### ISSUE TITLE
No support for relative paths

### ISSUE THREAD

**Issue by lewisclement** [artemanufrij/graphui#6]
When using url's to images, only absolute paths from root are supported. Otherwise a "Warning: No such file or directory while opening [file]" error is displayed, whereas this does work when calling the dot command from CLI.

**Comment by artemanufrij** [comment]
Hey @lewisclemen thank you for your feedback. could you send me an example you use in your case?

**Comment by lewisclement** [comment]
Well, for instance this case:

```
digraph example {
	rankdir=LR;

	// Actors
	{
		node [ shape=rectangle, image="actor.png", 
			width=2, height=2, fixedsize=true]

		Beheerder
		Ontwikkelaar
		Gebruiker
	}
}
```

When having the file "actor.png" in the same folder as the .gv file. 

And when I use an absolute path the graph is drawn, but the images aren't. But I don't think that's related to this problem, cause the CLI command produces expected results.

**Comment by artemanufrij** [comment]
thank you for your example. will test it when I'm back home.

**Comment by artemanufrij** [comment]
hey @lewisclement could you test current master branch please?

**Comment by artemanufrij** [comment]
Fixed released
