### ISSUE TITLE
Switch to meson

### ISSUE THREAD

**Issue by bilelmoussaoui** [artemanufrij/graphui#8]
Would you like to switch this app & the rest of your apps to meson please? Once it's done, they will all get a flatpak package :)

**Comment by artemanufrij** [comment]
@bilelmoussaoui sure... give me few days

**Comment by artemanufrij** [comment]
@bilelmoussaoui done!

**Comment by bilelmoussaoui** [comment]
Can you create a new tarball ?

**Comment by artemanufrij** [comment]
https://github.com/artemanufrij/graphui/releases

**Comment by bilelmoussaoui** [comment]
Yeah except that you forgot to update the data on the appdata file which makes it fail the tests because the date is in the future...

**Comment by artemanufrij** [comment]
@bilelmoussaoui done
